DjangoCRM/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('main.urls')),
    path('main/', include('main.urls')),
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
 
]

main/urls.py
from django.urls import path
from django.http import HttpResponse

from . import views

app_name = 'main'
urlpatterns = [ 
    path('', views.index, name='index'), 

    #services
    path('services/', views.services, name='services'),
    path('services/<int:service_id>/', views.services, name='services'), 
    path('service/add/', views.servicesadd, name='serviceadd'),
    path('service/delete/<int:service_id>', views.servicesdelete, name='servicedelete'),


    #customers
    path('customers/', views.customers, name='customers'),
    path('customers/<int:customer_id>/', views.customers, name='customers'),
    path('customer/add/', views.customeradd, name='customeradd'),
    path('customer/edit/<int:pk>/', views.customeredit, name='customeredit'),
    path('customer/delete/<int:pk>', views.customersdelete, name='customerdelete'),
    path('customer/services/<int:pk>', views.customeractiveservices, name='customerservices'),    

    #users
    path('register/', views.register, name='register'),

]

main/models.py
from django.db import models
from django.contrib import admin

class service(models.Model):
    name = models.CharField(max_length=128)
    
    def __str__(self):              
        return self.name

class customer(models.Model):
    name = models.CharField(max_length=128)
    phonenumber = models.CharField(max_length=128)
    myservices = models.ManyToManyField(service, through='customerservice', through_fields=('customer', 'service'))

    def __str__(self):              
        return self.name

class customerservice(models.Model):
    customer = models.ForeignKey(customer, on_delete = models.CASCADE)
    service = models.ForeignKey(service, on_delete = models.CASCADE)
    active = models.BooleanField(default=True)
    def __str__(self):
        return self.customer.name + " " +  self.service.name

class customerservice_inline(admin.TabularInline):
    model = customerservice
    extra = 1

class customerAdmin(admin.ModelAdmin):
    inlines = (customerservice_inline,)

main/forms.py
from django import forms
from .models import *
from django.forms.models import *
from crispy_forms.layout import Layout, Field, Fieldset, Div, HTML, ButtonHolder, Submit
from crispy_forms.layout import *
from crispy_forms.helper import FormHelper


class CustomerForm(forms.ModelForm):
    #myservices = forms.ModelMultipleChoiceField(widget = forms.CheckboxSelectMultiple,queryset = service.objects.all())
    #myservices = CServiceFormSet()
    class Meta:
        model = customer
        fields = ["name", "phonenumber"]


class CServiceForm(forms.ModelForm):
    class Meta:
        model = customerservice
        fields = ['service', 'active',]
        widgets = {
            'service': forms.Select(choices=service.objects.all()),
        }


CServiceFormSet = inlineformset_factory(customer, customerservice, CServiceForm, extra=1)

#service form
class ServiceForm(forms.ModelForm):
    class Meta:
        model = service
        exclude = ()

main/views.py
from django.http import HttpResponse, Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from .models import *
from .forms import *
from django.contrib.auth.forms import *
from django.contrib.auth import *
from django.forms import inlineformset_factory
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group

def index(request):
    if request.user.is_authenticated:
        return render(request, 'main/index.html')
    else :
        return redirect('/login/')
    

@login_required(login_url='/login')
def customers(request, customer_id=None):
    if customer_id is None :
        latest_customer = customer.objects.order_by('-name')
        context = {'latest_customer': latest_customer}      
        return render(request, 'main/customers.html', context)
    else :
        try:
            cc = customer.objects.get(pk=customer_id)
            srv = customerservice.objects.filter(customer=cc)
        except:
            raise Http404("Customer does not exist")
        return render(request, 'main/customer.html', {'customer': cc,"services":srv})

@login_required(login_url='/login')
def customeradd(request):
    try:
        form = CustomerForm(request.POST)
        if form.is_valid():
            cc = customer()
            cc.name = form.cleaned_data['name']
            cc.phonenumber = form.cleaned_data['phonenumber']
            # for f in form.cleaned_data['myservices']:
            #     cs = customerservice()
            #     cs.customer = cc
            #     cs.service = f
            #     cs.save()                                
            cc.save()
        
        newid = cc.pk
        return HttpResponseRedirect(reverse('main:customeredit', kwargs={'pk': newid}))
    except:
        return HttpResponseRedirect(reverse('main:customers'))
        
@login_required(login_url='/login')
def customeredit(request,pk):
    cc = get_object_or_404(customer, pk=pk)
    FormSet = inlineformset_factory(customer, customerservice, form=CServiceForm,extra=1)

    if request.method == 'POST':
        form = CustomerForm(request.POST)
        formset = FormSet(request.POST, instance=cc)

        if form.is_valid():
            cc.name = form.cleaned_data['name']
            cc.phonenumber = form.cleaned_data['phonenumber']
            #services here
            
            if formset.is_valid():
                formset.save()

            cc.save()
            # redirect to a new URL:
            return HttpResponseRedirect(reverse('main:customers'))

    formset = FormSet(instance=cc,)
    context = {
        "formset": formset,
        'form': CustomerForm(initial={'name': cc.name, 'phonenumber':cc.phonenumber }),
        'instance': cc,
    }

    return render(request, 'main/customeredit.html', context)

@login_required(login_url='/login')
def customersdelete(request,pk):
    try:
        cc = customer.objects.get(pk=pk)
        cc.delete()
        return redirect('main:customers')        
    except:
        return redirect('main:customers')

def customeractiveservices(request,pk):
    try :
        cc = customer.objects.get(pk=pk)
        srv = customerservice.objects.filter(customer=cc,active=True)
        
    except :
        raise Http404("Customer does not exist")

    return render(request, 'main/customerservices.html', {'customer': cc,"services":srv})


#=============================================================#
@login_required(login_url='/login')
def services(request, service_id=None):
    if service_id is None :
        latest_service = service.objects.order_by('-name')
        context = {'latest_service': latest_service,}      
        return render(request, 'main/services.html', context)

    else :
        try:
            cc = service.objects.get(pk=service_id)
        except:
            raise Http404("Service does not exist")
        return render(request, 'main/service.html', {'service': cc})

@login_required(login_url='/login')
def servicesadd(request):
    try:
        form = ServiceForm(request.POST)
        if form.is_valid():
            ss = service()
            ss.name = form.cleaned_data['name']                               
            ss.save()
            
        return HttpResponseRedirect(reverse('main:services'))
    except:
        return HttpResponseRedirect(reverse('main:services'))

@login_required(login_url='/login')
def servicesdelete(request,service_id):
    try:
        cc = service.objects.get(pk=service_id)
        cc.delete()

        return redirect('main:services')        
    except:
        return redirect('main:services')

#==============================================================#

def register(request): 
    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            user = form.save()
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password1"]
            #add group if doesn't exist
            group_name = 'employee'
            try:
                gg = Group.objects.get(name=group_name)
                user.groups.add(gg)
                gg.save()

            except Group.DoesNotExist:   
                gg = Group()
                gg.name = group_name
                gg.save()
                user.groups.add(gg)         

            user = authenticate(username=username, password=password)
            login(request,user)
            return redirect('/main')            

    else :
        form = UserCreationForm()

        
    context = {'form' : form}
    return render(request, 'registration/register.html', context)

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Django-CRM</title>

    {% load static %}

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/datatable.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" >
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
        <div class="container">
            <a class="navbar-brand" href="#">Django-CRM</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:services' %}">Services</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:customers' %}">Customers</a>
                    </li>
                    {% if user.is_authenticated %}                        
                        <li class="nav-item">
                            <a class="nav-link" href="#">Welcome {{ request.user.username }} </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">Logout </a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:register' %}">Register</a>
                        </li>

                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <!-- Page Content -->
    <div class="container">
        <div class="row">
            <div  class="col-lg-12">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>


<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.formset/1.2.2/jquery.formset.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>

<script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

<script src="{% static 'js/main.js' %}"></script>
{% block scripts %}

{% endblock %}
</html>

main/templates/main/customer.html
{% extends 'main/base.html' %}

{% block content %}
<div class="row">
    <div class="card mt-5 col-8">
        <div class="card-body">
            <h5 class="card-title"> Customer Details</h5>
            
            <ul class="list-unstyled">
                    <li class="lead">Name : <span class="text-dark">{{ customer.name }}</span></li>
                    <li class="lead">Phone number : <span class="text-dark">{{ customer.phonenumber }}</span></li>
            </ul>
            <h6 class="card-subtitle mb-2 text-muted text-left">Services</h6>
            <ul class="list-unstyled">
                {% for f in services %}
                    <li class="lead"><span class="text-dark">{{ f.service.name  }} - </span>
                    {% if f.active  %}
                        <span class="text-success"> Active </span>
                    {% else %}
                        <span class="text-danger"> Not Active </span> 
                    {% endif %}
                    </li>
                {% endfor %}
            </ul>

            <a class="float-left btn btn-dark" href="{% url 'main:customers' %}"> Back </a>
        </div>
    </div>

</div>



{% endblock  %}

main/templates/main/customeredit.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="card mt-5">
    <div class="card-body">
        <h4 class="card-title">Edit Customer </h4>

        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}

            <div id="formset-wrapper">
                <div class="items" id="formsets">
                    {{ formset|crispy }}
                </div>
                <button type="button" class="btn btn-primary btn-sm mb-2" id="add-item">Add row</button>
            </div>
            <button type="submit" class="btn btn-primary" >Save</button>
            <a href="{% url 'main:customers' %}" class="btn btn-dark" >Back</a>        
        </form>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    $(document).ready(function(){
        //get html of first formset
        $("#formset-wrapper .items .multiField:last .form-group:last").remove();
        var formhtml = $("#formset-wrapper .items .multiField:last").html();
        var initiali = $('#formset-wrapper .items .multiField').length-1;

        $('#formset-wrapper .items .multiField select option:selected').each(function(){
            if($(this).val() != ''){
                $('#formset-wrapper .items .multiField:last select option[value="'+$(this).val() + '"]').remove();
            }
        });

        $(document).on('click','#add-item',function(){
            console.log($('#formset-wrapper .items .multiField:last select option:selected').val());
            if($('#formset-wrapper .items .multiField:last select option:selected').val() !== ''){
                var rr = $('#formset-wrapper .items .multiField').length;
                var temphtml = formhtml.split(initiali).join(rr);
                $("#formsets").append('<div class="multiField">' + temphtml +'</div>');
                $("#id_customerservice_set-TOTAL_FORMS").val(parseInt($("#id_customerservice_set-TOTAL_FORMS").val())+1);
                $('#formset-wrapper .items .multiField select option:selected').each(function(){
                    if($(this).val() != ''){
                        $('#formset-wrapper .items .multiField:last select option[value="'+$(this).val() + '"]').remove();
                    }
                });
            }

        });
    });
</script>    
{% endblock %}

main/templates/main/customers.html
{% extends 'main/base.html' %}

{% block content %}
<div class="card mt-5">
    <div class="card-body">
        <h4 class="card-title">Customers</h4>
        <div class="row col-3">
            <button class="btn btn-info mb-3 text-left" type="button" data-toggle="collapse"
                data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample"> Add Customer
            </button>
        </div>
        <div class="row ml-1 mb-2">
            <form class="form collapse" id="collapseExample" action="{% url 'main:customeradd'%}" method="post">
                {% csrf_token %}
                {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

                <div class="form-group">
                    <label for="name" class="form-label">Customer Name</label>
                    <input type="text" name="name" class="form-control">
                </div>
                <div class="form-group">
                    <label for="phonenumber" class="form-label">Phone Number</label>
                    <input type="text" name="phonenumber" class="form-control">
                </div>

                <input type="submit" class="btn btn-primary float-left" value="Add">
            </form>
        </div>
        
        <table id="datatable" class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">#</th>  
                    <th scope="col">Name</th>
                    <th scope="col">Phone Number</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% if latest_customer %}
                    {% for cc in latest_customer %}
                    <tr>
                        <td scope="row">{{  forloop.counter }}</td>
                        <td><a href="{% url 'main:customers' cc.id %}">{{ cc.name }}</a></td>
                        <td>{{ cc.phonenumber }}</td>
                        <td>
                            <a style="float: right;margin:0 10px" href="{% url 'main:customerdelete' cc.id %}"> Delete </a>
                            <a style="float: right;margin:0 10px" href="{% url 'main:customeredit' cc.id %}"> Edit </a>
                            <a href="#" class="serv-btn"  data-url="{% url 'main:customerservices' cc.id %}" style="float: right;margin:0 10px" > Active Services </a>
                        </td>

                    </tr>
                    {% endfor %}
                {% endif %}
            </tbody>
        </table>
       
    </div>
</div>

{% endblock  %}
{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.js" integrity="sha256-tcqPYPyxU+Fsv5sVdvnxLYJ7Jq9wWpi4twZbtZ0ubY8=" crossorigin="anonymous"></script>
<script>
    $(document).ready(function(){
        $("#datatable").DataTable();

        $(document).on('click','.serv-btn',function(e){
            e.preventDefault();
            var url = $(this).data('url');
            $.ajax({
                url: url,
                method: "GET",
                success : function(data){
                    bootbox.alert({
                        title: "Customer Active Services",
                        message: data,
                    });
                }
            });
        });
    });
</script>

{% endblock  %}

main/templates/main/customerservices.html
<h5 class="card-title"> Customer : {{ customer.name }}</h5>


<ul class="list-unstyled">
    {% if services %}
        <li class="lead"><span class="text-dark">Services</span></li>

        {% for f in services %}
            <li class="lead"><span class="text-dark text-black-50">{{ f.service.name  }} </span></li>
        {% endfor %}
    {% else %}
        <li class="lead"><span class="text-dark">No active services </span></li>
    {% endif %}
</ul>

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}

<div class="text-center">

    <h2 class="mt-5">Welcome to Django-CRM</h2>
    <p class="lead">the simple Django based CRM solution</p>

</div>


{% endblock  %}

main/templates/main/service.html
{% extends 'main/base.html' %}

{% block content %}

<div class="row">
    <div class="card mt-5 col-8">
        <div class="card-body">
            <h5 class="card-title"> Service Details</h5>
            <h6 class="card-subtitle mb-2 text-muted text-left"></h6>
            <ul class="list-unstyled">
                    <li class="lead">Name : <span class="text-dark">{{ service.name }}</span></li>
            </ul>
            <a class="float-left btn btn-dark" href="{% url 'main:services' %}"> Back </a>
        </div>
    </div>
</div>

{% endblock  %}

main/templates/main/services.html
{% extends 'main/base.html' %}

{% block content %}
<div class="card mt-5">
    <div class="card-body">
        <h4 class="card-title">Services</h4>
        <div class="row col-3">
            <button class="btn btn-info mb-3 text-left" type="button" data-toggle="collapse"
                data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample"> Add Service
            </button>
        </div>
        <div class="row ml-1 mb-2">
            <form class="form collapse" id="collapseExample" action="{% url 'main:serviceadd'%}" method="post">
                {% csrf_token %}
                {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

                <div class="form-group">
                    <label for="name" class="form-label">Service Name</label>
                    <input type="text" name="name" class="form-control">
                </div>

                <input type="submit" class="btn btn-primary float-left" value="Add">
            </form>
        </div>
        <table id="datatable" class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% if latest_service %}
                {% for cc in latest_service %}
                <tr>
                    <td scope="row">{{  forloop.counter }}</td>
                    <td><a href="{% url 'main:services' cc.id %}">{{ cc.name }}</a></td>
                    <td><a style="float: right;" href="{% url 'main:servicedelete' cc.id %}"> Delete </a></td>
                </tr>
                {% endfor %}
                {% endif %}
            </tbody>
        </table>

    </div>
</div>

{% endblock  %}

{% block scripts %}
<script>
    $(document).ready(function () {
        $("#datatable").DataTable();
    });
</script>

{% endblock  %}